# Generated by Django 5.1.3 on 2024-12-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='state',
            new_name='province',
        ),
    ]
