# Generated by Django 5.1.1 on 2024-12-07 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_profile_old_cart_alter_profile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alternate_names',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
